- name: Install Grafana on EC2 instance
  become: yes
  hosts: all
  remote_user: ubuntu
  vars:
    grafana_version: "8.2.1"  # Versão do Grafana que você deseja instalar

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install dependencies
      package:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - software-properties-common
        - ca-certificates
      when: ansible_os_family == "Debian"

    - name: Install nessesary package
      apt: 
          name: apt-transport-https
          state: present
          update_cache: yes

    - name: add grafana gpg key
      shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

    - name: add grafana repo 
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana

    - name: Install grafana
      apt: 
          name: grafana
          state: present
          update_cache: yes

    - name: Enable and start grafana service
      service:
        name: grafana-server
        enabled: yes
        state: started